{% set version = "0.0.5" %}

package:
  name: mplleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mplleaflet/mplleaflet-{{ version }}.tar.gz
  sha256: 049e0b91797ce5b462853395138161fed9e8dfc1f4723f482ebb0739a0bbd289

build:
  number: 4
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2
    - six
    - matplotlib-base

test:
  imports:
    - mplleaflet

about:
  home: https://github.com/jwass/mplleaflet
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: 'Convert Matplotlib plots into Leaflet web maps'

extra:
  recipe-maintainers:
    - jwass
    - ocefpaf
