travis:
  secure:
    BINSTAR_TOKEN: Mc6G7P9Ilz03+nV8J9Fu7UEmKHMReDGR8ooFS62WqFXgixqnz7dJ59Ysn+2sosKJoKUq/97Q8qPUjasyNN9XsL14NIdmpHyS2cz2xdQwLGUpx3KB0zWMl2YktZWnAtZ+VchddJWrF+UXyKUPIdYg4gaQvpk8Aqicr4NKAoA+b3rcGpbW0Qov40OXgs6DyFyu3A/m0+BtiIZ0Kxm6zronO8VSmEi10q9X8L1lQLOjmaqdAN5i58IslS4XZ2TOqsw4WU93psGWZDeau2l45jNMTmtCuBKjRBV07rXfay9+6tMxKtfDtm5XjAa5p4BKwxR6/KpiXKq632HNRhcRMUSoDh87alPgGK3m+OQ43T9i6Rj901kRmuJ4+2OvYBXR0DxDs2w860lylYfbzt60QUZ+OFO7xPsZTVd7cpx2u87RwZQXc4qth8lWCWtbDjsITma7qH2aZe/AYfCVj8v2ulGYke+puDwejRqpixGuwm/8uIL7dkOrK4JbnudlmBgH4CfC9y6isKcDxqaK5xCtWp9wlDsuARBaKCkh3m4WGR4xQ5kh/4osY/VBSdS3dnPU8HqUjz2pQM0dCz8bqwPXUCpn605CqOwNVhKX6JAq3tR9aneRPEc2yKC7Y79cb3ivmeIXKAVRBW/Q1cM40RifXGxdGIDA382+0GxA4AV3/FC6XQo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
