travis:
  secure:
    BINSTAR_TOKEN: TYJ49XsE3xsNnppB67Ntt8Pq/BxFVy8FWf+bdtCAH3nMMijzV3dIPXMlPfpxfEVL9+bK5lLxbEQ88kvM1JoukuSS+A1+39sREQS2RdpM7jjCWB7KLbF63M9zkYvZG3oNLx/XLt1yDDiSXzSoxnEYiTAFdTH8Bm1iQCJ2n+jpPeY90U09kxxO0dgbyZbOl32ztZl6qXAZIuOJzF/Huk/2GC/YsCHP1dVB0Nq04TjMK1tMTg9y4jB0b78CZM0T3/AGBFE4PCNNg5ZXddYcT5Fptccf0veudReSiN5+J9vJAd2BLBKYN5qCNFJFkMgeeN7/AQbC95zGZR8ucbeu//wL/AnaTEw7vV5GwNxPx7Cgx4YJLGahfGWWwOvTLBmSPPwd2s96/B9/7cWs8oZFE2O1NSWQF0DNwPHzjeY3bppQSMP58RYRnbSIwcaG16qfjE7ULJDyq+sYxDGNBaD0jlKhyBwycBo1bvHjXr9ZMXtMcs4/PpWtgOanAs9EZtSizr6dXKMvAQAyAcspYrw4qildeuoNLKrcoaFh1b8+/pNJEIaTo9L9bfcpaBmJ8Z13SrGtXj2QBq3ovK0CfQp3aFASz/uVUQWQNVjvV41tdBnZPy+a7yM4eQtgQXCsqAkrwGEvmUZeQWaCKdjN2YWYaGzjsbLQ1yB3mwGbtFVrB2qR+sc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
